// <auto-generated />
using System;
using AspireApp1.ApiService.Database_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspireApp1.ApiService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240930200528_data")]
    partial class data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspireApp1.ApiService.Models.Pago", b =>
                {
                    b.Property<Guid>("Id_Pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Banco_Pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Concepto_Pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cuenta_Pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha_Limite_Pago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto_Pago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Referencia_Pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sucursal_Pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Pago");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("AspireApp1.ApiService.Models.Solicitante", b =>
                {
                    b.Property<Guid>("Id_Solicitante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha_Nacimiento_Solicitante")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_Solicitante")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id_Solicitante");

                    b.ToTable("Solicitante", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Solicitante = new Guid("402c2777-24a5-43ba-b05e-5ffe9a33b56a"),
                            Fecha_Nacimiento_Solicitante = new DateTime(1995, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre_Solicitante = "Juan Pérez"
                        },
                        new
                        {
                            Id_Solicitante = new Guid("402c2777-24a5-43ba-b05e-5ffe9a33b56b"),
                            Fecha_Nacimiento_Solicitante = new DateTime(1998, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre_Solicitante = "María López"
                        },
                        new
                        {
                            Id_Solicitante = new Guid("402c2777-24a5-43ba-b05e-5ffe9a33b56c"),
                            Fecha_Nacimiento_Solicitante = new DateTime(2000, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre_Solicitante = "Carlos Ramírez"
                        });
                });

            modelBuilder.Entity("AspireApp1.ApiService.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("AspireApp1.ApiService.Models.Pago", b =>
                {
                    b.HasOne("AspireApp1.ApiService.Models.Solicitante", "Solicitante")
                        .WithMany("Pagos")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("AspireApp1.ApiService.Models.Solicitante", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
