// <auto-generated />
using System;
using AspireApp1.ApiService.Database_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspireApp1.ApiService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241017181454_v-4")]
    partial class v4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspireApp1.ApiService.Models.Alumno", b =>
                {
                    b.Property<Guid>("Id_Alumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido_Materno_Alumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido_Paterno_Alumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bachillerato_Alumno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carrera_Alumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curp_Alumno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_Alumno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Nacimiento_Alumno")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_Alumno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Sexo_Alumno")
                        .HasColumnType("int");

                    b.HasKey("Id_Alumno");

                    b.ToTable("Alumno", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Alumno = new Guid("802c2777-24a5-43ba-b05e-5ffe9a33b56a"),
                            Apellido_Materno_Alumno = "Vega",
                            Apellido_Paterno_Alumno = "Torres",
                            Carrera_Alumno = "Administración de empresas",
                            Fecha_Nacimiento_Alumno = new DateTime(2000, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre_Alumno = "Miguel",
                            Sexo_Alumno = 0
                        },
                        new
                        {
                            Id_Alumno = new Guid("802c2777-24a5-43ba-b05e-5ffe9a33b56b"),
                            Apellido_Materno_Alumno = "Díaz",
                            Apellido_Paterno_Alumno = "González",
                            Carrera_Alumno = "Gastronomía",
                            Fecha_Nacimiento_Alumno = new DateTime(2001, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre_Alumno = "Sofía",
                            Sexo_Alumno = 1
                        },
                        new
                        {
                            Id_Alumno = new Guid("802c2777-24a5-43ba-b05e-5ffe9a33b56c"),
                            Apellido_Materno_Alumno = "Mendoza",
                            Apellido_Paterno_Alumno = "Reyes",
                            Carrera_Alumno = "Derecho",
                            Fecha_Nacimiento_Alumno = new DateTime(1999, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre_Alumno = "Diego",
                            Sexo_Alumno = 0
                        });
                });

            modelBuilder.Entity("AspireApp1.ApiService.Models.Pago", b =>
                {
                    b.Property<Guid>("Id_Pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Banco_Pago")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Concepto_Pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cuenta_Pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha_Limite_Pago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto_Pago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Referencia_Pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sucursal_Pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Pago");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Pago", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Pago = new Guid("102c2777-24a5-43ba-b05e-5ffe9a33b56b"),
                            Banco_Pago = 1,
                            Concepto_Pago = "Inscripción",
                            Cuenta_Pago = "1234567890",
                            Fecha_Limite_Pago = new DateTime(2024, 11, 16, 12, 14, 53, 302, DateTimeKind.Local).AddTicks(5724),
                            Monto_Pago = 1800m,
                            Referencia_Pago = "REF12345",
                            SolicitanteId = new Guid("402c2777-24a5-43ba-b05e-5ffe9a33b56a"),
                            Sucursal_Pago = "9865"
                        },
                        new
                        {
                            Id_Pago = new Guid("202c2777-24a5-43ba-b05e-5ffe9a33b56b"),
                            Banco_Pago = 0,
                            Concepto_Pago = "Colegiatura",
                            Cuenta_Pago = "0987654321",
                            Fecha_Limite_Pago = new DateTime(2024, 11, 1, 12, 14, 53, 302, DateTimeKind.Local).AddTicks(5771),
                            Monto_Pago = 2000m,
                            Referencia_Pago = "REF67890",
                            SolicitanteId = new Guid("402c2777-24a5-43ba-b05e-5ffe9a33b56b"),
                            Sucursal_Pago = "9865"
                        },
                        new
                        {
                            Id_Pago = new Guid("302c2777-24a5-43ba-b05e-5ffe9a33b56b"),
                            Banco_Pago = 1,
                            Concepto_Pago = "Materiales",
                            Cuenta_Pago = "1122334455",
                            Fecha_Limite_Pago = new DateTime(2024, 12, 1, 12, 14, 53, 302, DateTimeKind.Local).AddTicks(5778),
                            Monto_Pago = 1700m,
                            Referencia_Pago = "REF11223",
                            SolicitanteId = new Guid("402c2777-24a5-43ba-b05e-5ffe9a33b56c"),
                            Sucursal_Pago = "9865"
                        },
                        new
                        {
                            Id_Pago = new Guid("102c2777-24a5-43ba-b05e-5ffe9a33b56d"),
                            Banco_Pago = 0,
                            Concepto_Pago = "Inscripción",
                            Cuenta_Pago = "1234567890",
                            Fecha_Limite_Pago = new DateTime(2024, 11, 16, 12, 14, 53, 302, DateTimeKind.Local).AddTicks(5783),
                            Monto_Pago = 1900m,
                            Referencia_Pago = "REF12345",
                            SolicitanteId = new Guid("402c2777-24a5-43ba-b05e-5ffe9a33b56c"),
                            Sucursal_Pago = "9865"
                        });
                });

            modelBuilder.Entity("AspireApp1.ApiService.Models.Solicitante", b =>
                {
                    b.Property<Guid>("Id_Solicitante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha_Nacimiento_Solicitante")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_Solicitante")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id_Solicitante");

                    b.ToTable("Solicitante", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Solicitante = new Guid("402c2777-24a5-43ba-b05e-5ffe9a33b56a"),
                            Fecha_Nacimiento_Solicitante = new DateTime(1995, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre_Solicitante = "Juan Pérez"
                        },
                        new
                        {
                            Id_Solicitante = new Guid("402c2777-24a5-43ba-b05e-5ffe9a33b56b"),
                            Fecha_Nacimiento_Solicitante = new DateTime(1998, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre_Solicitante = "María López"
                        },
                        new
                        {
                            Id_Solicitante = new Guid("402c2777-24a5-43ba-b05e-5ffe9a33b56c"),
                            Fecha_Nacimiento_Solicitante = new DateTime(2000, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre_Solicitante = "Carlos Ramírez"
                        });
                });

            modelBuilder.Entity("AspireApp1.ApiService.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido_Materno_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido_Paterno_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena_Usuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaNacimiento_Usuario")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_Usuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Usuario = new Guid("702c2777-24a5-43ba-b05e-5ffe9a33b56a"),
                            Apellido_Materno_Usuario = "Hernández",
                            Apellido_Paterno_Usuario = "García",
                            Contrasena_Usuario = "1234",
                            FechaNacimiento_Usuario = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre_Usuario = "Zein"
                        },
                        new
                        {
                            Id_Usuario = new Guid("702c2777-24a5-43ba-b05e-5ffe9a33b56b"),
                            Apellido_Materno_Usuario = "López",
                            Apellido_Paterno_Usuario = "Martínez",
                            Contrasena_Usuario = "securepassword",
                            FechaNacimiento_Usuario = new DateTime(1992, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre_Usuario = "Ana"
                        },
                        new
                        {
                            Id_Usuario = new Guid("702c2777-24a5-43ba-b05e-5ffe9a33b56c"),
                            Apellido_Materno_Usuario = "Ramírez",
                            Apellido_Paterno_Usuario = "Sánchez",
                            Contrasena_Usuario = "pass456",
                            FechaNacimiento_Usuario = new DateTime(1988, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre_Usuario = "Pedro"
                        });
                });

            modelBuilder.Entity("AspireApp1.ApiService.Models.Pago", b =>
                {
                    b.HasOne("AspireApp1.ApiService.Models.Solicitante", "Solicitante")
                        .WithMany("Pagos")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("AspireApp1.ApiService.Models.Solicitante", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
