// <auto-generated />
using System;
using API_UBAM.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_UBAM.Migrations
{
    [DbContext(typeof(UbamDbContext))]
    [Migration("20241027195036_Create_Database")]
    partial class Create_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_UBAM.Models.Alumno", b =>
                {
                    b.Property<Guid>("Id_Alumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Grupo_Alumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Id_Carrera")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Persona")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id_Alumno");

                    b.HasIndex("Id_Carrera");

                    b.HasIndex("Id_Persona")
                        .IsUnique();

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id_Alumno = new Guid("e2346f6c-6789-0123-45fa-cdef67890123"),
                            Grupo_Alumno = "Sistemas 101",
                            Id_Carrera = new Guid("c0124d4a-4567-8901-23de-fabc45678901"),
                            Id_Persona = new Guid("c450de8c-7993-554a-af11-857ab5a2c95b")
                        });
                });

            modelBuilder.Entity("API_UBAM.Models.Carrera", b =>
                {
                    b.Property<Guid>("Id_Carrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nombre_Carrera")
                        .HasColumnType("int");

                    b.HasKey("Id_Carrera");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            Id_Carrera = new Guid("c0124d4a-4567-8901-23de-fabc45678901"),
                            Nombre_Carrera = 18
                        },
                        new
                        {
                            Id_Carrera = new Guid("d1235e5b-5678-9012-34ef-bcde56789012"),
                            Nombre_Carrera = 0
                        });
                });

            modelBuilder.Entity("API_UBAM.Models.Docente", b =>
                {
                    b.Property<Guid>("Id_Docente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Persona")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id_Docente");

                    b.HasIndex("Id_Persona")
                        .IsUnique();

                    b.ToTable("Docentes");

                    b.HasData(
                        new
                        {
                            Id_Docente = new Guid("f3457e7d-7890-1234-56ab-defa78901234"),
                            Id_Persona = new Guid("d560ef9d-88a4-665b-b012-968bc6b3d06c")
                        });
                });

            modelBuilder.Entity("API_UBAM.Models.Persona", b =>
                {
                    b.Property<Guid>("Id_Persona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido_Materno_Persona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido_Paterno_Persona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curp_Persona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha_Nacimiento_Persona")
                        .HasColumnType("date");

                    b.Property<string>("Nombre_Persona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sexo_Persona")
                        .HasColumnType("int");

                    b.HasKey("Id_Persona");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id_Persona = new Guid("b350ce7b-6982-4439-9f00-7469a49e1b84"),
                            Apellido_Materno_Persona = "Rangel",
                            Apellido_Paterno_Persona = "Contreras",
                            Curp_Persona = "CORR900524HDFRRL04",
                            Fecha_Nacimiento_Persona = new DateOnly(2003, 9, 25),
                            Nombre_Persona = "Ramiro Zein",
                            Sexo_Persona = 0
                        },
                        new
                        {
                            Id_Persona = new Guid("c450de8c-7993-554a-af11-857ab5a2c95b"),
                            Apellido_Materno_Persona = "Hernández",
                            Apellido_Paterno_Persona = "López",
                            Curp_Persona = "LOHM920815MDFRRL05",
                            Fecha_Nacimiento_Persona = new DateOnly(1992, 8, 15),
                            Nombre_Persona = "María",
                            Sexo_Persona = 1
                        },
                        new
                        {
                            Id_Persona = new Guid("d560ef9d-88a4-665b-b012-968bc6b3d06c"),
                            Apellido_Materno_Persona = "Martínez",
                            Apellido_Paterno_Persona = "Ramírez",
                            Curp_Persona = "RAMC850310HDFRRL06",
                            Fecha_Nacimiento_Persona = new DateOnly(1985, 3, 10),
                            Nombre_Persona = "Carlos",
                            Sexo_Persona = 0
                        },
                        new
                        {
                            Id_Persona = new Guid("e670f0ae-99b5-776c-c123-a79cd7c4e17d"),
                            Apellido_Materno_Persona = "Silva",
                            Apellido_Paterno_Persona = "González",
                            Curp_Persona = "GOSA951205MDFRRL07",
                            Fecha_Nacimiento_Persona = new DateOnly(1995, 12, 5),
                            Nombre_Persona = "Ana",
                            Sexo_Persona = 1
                        });
                });

            modelBuilder.Entity("API_UBAM.Models.Rol", b =>
                {
                    b.Property<Guid>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nombre_Rol")
                        .HasColumnType("int");

                    b.HasKey("Id_Rol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id_Rol = new Guid("f7801a1f-1234-5678-90ab-cdef12345678"),
                            Nombre_Rol = 0
                        },
                        new
                        {
                            Id_Rol = new Guid("f7801a1f-1234-5678-90ab-cdef12345679"),
                            Nombre_Rol = 1
                        },
                        new
                        {
                            Id_Rol = new Guid("f7801a1f-1234-5678-90ab-cdef12345680"),
                            Nombre_Rol = 2
                        });
                });

            modelBuilder.Entity("API_UBAM.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clave_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estatus_Usuario")
                        .HasColumnType("int");

                    b.Property<Guid>("Id_Persona")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("Id_Persona")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id_Usuario = new Guid("a8902b2a-2345-6789-01bc-def123456789"),
                            Clave_Usuario = "$2a$11$CP.9YFNoCapDBQqN2lCLBu3Q61gNwOOjAGg8u/4sw5E.ym1244.N2",
                            Estatus_Usuario = 1,
                            Id_Persona = new Guid("b350ce7b-6982-4439-9f00-7469a49e1b84"),
                            Nombre_Usuario = "ramiro.zein"
                        },
                        new
                        {
                            Id_Usuario = new Guid("b9013c3b-3456-7890-12cd-efab34567890"),
                            Clave_Usuario = "$2a$11$lr8gRm9jUuSvF7Kabr9s2eD3fSCY4/uTHHbNMD/hPnMnN5Us2CwOq",
                            Estatus_Usuario = 1,
                            Id_Persona = new Guid("c450de8c-7993-554a-af11-857ab5a2c95b"),
                            Nombre_Usuario = "maria.lopez"
                        });
                });

            modelBuilder.Entity("API_UBAM.Models.Usuario_Rol", b =>
                {
                    b.Property<Guid>("Id_Usuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("Id_Rol")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.HasKey("Id_Usuario", "Id_Rol");

                    b.HasIndex("Id_Rol");

                    b.ToTable("Usuario_Roles");

                    b.HasData(
                        new
                        {
                            Id_Usuario = new Guid("a8902b2a-2345-6789-01bc-def123456789"),
                            Id_Rol = new Guid("f7801a1f-1234-5678-90ab-cdef12345678")
                        },
                        new
                        {
                            Id_Usuario = new Guid("b9013c3b-3456-7890-12cd-efab34567890"),
                            Id_Rol = new Guid("f7801a1f-1234-5678-90ab-cdef12345680")
                        });
                });

            modelBuilder.Entity("API_UBAM.Models.Alumno", b =>
                {
                    b.HasOne("API_UBAM.Models.Carrera", "Carrera")
                        .WithMany("Alumnos")
                        .HasForeignKey("Id_Carrera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_UBAM.Models.Persona", "Persona")
                        .WithOne("Alumno")
                        .HasForeignKey("API_UBAM.Models.Alumno", "Id_Persona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("API_UBAM.Models.Docente", b =>
                {
                    b.HasOne("API_UBAM.Models.Persona", "Persona")
                        .WithOne("Docente")
                        .HasForeignKey("API_UBAM.Models.Docente", "Id_Persona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("API_UBAM.Models.Usuario", b =>
                {
                    b.HasOne("API_UBAM.Models.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("API_UBAM.Models.Usuario", "Id_Persona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("API_UBAM.Models.Usuario_Rol", b =>
                {
                    b.HasOne("API_UBAM.Models.Rol", "Rol")
                        .WithMany("Usuario_Roles")
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_UBAM.Models.Usuario", "Usuario")
                        .WithMany("Usuario_Roles")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API_UBAM.Models.Carrera", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("API_UBAM.Models.Persona", b =>
                {
                    b.Navigation("Alumno")
                        .IsRequired();

                    b.Navigation("Docente")
                        .IsRequired();

                    b.Navigation("Usuario")
                        .IsRequired();
                });

            modelBuilder.Entity("API_UBAM.Models.Rol", b =>
                {
                    b.Navigation("Usuario_Roles");
                });

            modelBuilder.Entity("API_UBAM.Models.Usuario", b =>
                {
                    b.Navigation("Usuario_Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
